### PR TITLE
feat: gather-telemetry now takes optional puppeteerArgs resolves #8

### LINKED ISSUE #8: Support passing puppeteer arguments
For debugging purposes, it's useful to be able to pass Puppeteer arguments during invocation. For example, on debugging the ember-native-class-codemod, I ended up needing to `volta install` the codemod and then manually modify the Puppeteer arguments in the installation location on disk to launch it in non-headless mode in order to understand the problem we were seeing.

**Proposal:** All exported functions which result in a Puppeteer launch should take as their second argument a hash of Puppeteer options, and this can be documented in their public APIs in the README.

### PR DESCRIPTION
**Pull request by scottkidder**

### CODE REVIEW

**Review by rwjblue — APPROVED** [review]
Seems OK to me, @pzuraq / @NullVoxPopuli any objections?

**Comment by rwjblue** [comment]
@scottkidder - The CI failure here is due to linting:

```
/home/travis/build/ember-codemods/ember-codemods-telemetry-helpers/lib/gather/gather-telemetry.js
  6:67  error  Replace `=` with `·=·`  prettier/prettier

```

Probably can fix via `yarn lint:js --fix`

**Review by NullVoxPopuli — APPROVED** [review]
Seems fine to me!

**Review by pzuraq — APPROVED** [review]

**Comment by scottkidder** [comment]
Thanks!

**Pull request merged**
