### PR TITLE
Support add-on dummy app files

### LINKED ISSUE #39: Support add-on dummy apps
https://github.com/ember-codemods/ember-codemods-telemetry-helpers/blob/80b90606b22742510f6376f84eadd5324da0e760/lib/utils/get-module-path-for.js#L41 needs update to resolve `dummy` in addition to `addon` and `addon-test-support`

### PR DESCRIPTION
**Pull request by xg-wang**
Fixes https://github.com/ember-codemods/ember-codemods-telemetry-helpers/issues/39 https://github.com/ember-codemods/ember-codemods-telemetry-helpers/issues/34

### CODE REVIEW

**Comment by xg-wang** [comment]
Tested locally to patch the diff, I can transform the dummy app file without changing ember-native-class-codemod

**Comment by rwjblue** [comment]
CI doesn't seem to be running, I've submitted https://github.com/ember-codemods/ember-codemods-telemetry-helpers/pull/41 to move to GitHub Actions instead of TravisCI.

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
@xg-wang - Some linting failures to fixup, but otherwise looks good.

**Comment by xg-wang** [comment]
@rwjblue oh I missed that, thanks for reminding

**Comment by elwayman02** [comment]
@rwjblue @xg-wang anything stopping this from shipping?

**Comment by elwayman02** [comment]
Bump

**Pull request merged**
