### PR TITLE
`analyzeEmberObject()` exits too early not allowing to enumerate `helpers`

### PR DESCRIPTION
**Pull request by tylerturdenpants**

### CODE REVIEW

**Comment by tylerturdenpants** [comment]
@rwjblue I made one small error in the flow logic.  Sorry!

**Comment by tylerturdenpants** [comment]
@rwjblue Maybe a 1.0.1 release?

**Comment by NullVoxPopuli** [comment]
This fixes some things for no-implicit this! <3

**Comment by tylerturdenpants** [comment]
@NullVoxPopuli I’m pretty mad at myself for not catching this.

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
The CI failures seem related to the changes:

```
● Provide a personalized `Gathering Function` › can determine components with a robust function
    expect(received).toEqual(expected) // deep equality
    Expected: 29
    Received: 34
      50 |     await gatherTelemetry('http://localhost:4200', analyzeEmberObject);
      51 |     let telemetry = getTelemetry();
    > 52 |     expect(Object.values(telemetry).filter(Boolean).length).toEqual(29);
         |                                                             ^
      53 |   });
      54 | 
      55 |   test('can handle external functions', async () => {
      at Object.toEqual (lib/gather/gather-telemetry.test.js:52:61)

```

**Comment by tylerturdenpants** [comment]
Let me fix this. Sorry for the inconvenience @rwjblue

**Comment by tylerturdenpants** [comment]
I will open a PR soon that has some fine grained tests.  I can see that the coverage is too low, and that is my fault.

**Comment by rwjblue** [comment]
> I can see that the coverage is too low, and that is my fault.

Nah, no worries!

**Review by rwjblue — APPROVED** [review]

**Comment by rwjblue** [comment]
Released in v1.0.1

**Pull request merged**
